import "./globals.scss";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "../components/error";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { mainApi } from "@/Utils/api";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const categories = await mainApi.getCategories();

  return (
    <html lang="ru">
      <body className='app'>
        <ErrorBoundary fallback={<Error />} >
          <Header categories={categories}/>
          {children}
          <Footer categories={categories}/>
        </ErrorBoundary>
      </body>
    </html>
  );
}
